
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-portal-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: Bearer  #JWT负载中拿到开头

#类型 1：七牛  2：阿里云  3：腾讯云
oss:
  type: 1
  domain: qgzz0alb0.hd-bkt.clouddn.com
  prefix:
  accessKey: 8nWf5ZuhQbn3jsMeEC5bgLAdwQQQUWA65iatx2wf
  secretKey: c35_gaBpub7zi-nGOpZ8DBkG0CUzP8Clh5D06scm
  bucketName: kaoyandang